### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by masterxilef** [Tympanix/Electorrent#1]
Hello, I tried to install on Windows on 2 different machines, one with Windows 7 and one with Windows 10, both 32 bit, and on both it failed, is there a prerequisite I need to install before?
Also, I notice it tries to install to the AppData folder, any chance of installing it to the Program Files folder.
If you need the log let me know, however, most of it it's in spanish...
Thanks.

**Comment by Tympanix** [comment]
Hi masterxilef.

Thank you for reporting the problem. My program is only available is 64 bit architectures (I will update the readme so reflect this). And yes - because of the installer (using the Squirrel framework), the app is installed to _AppData_ and not _Program Files_. No way around that. This is to avoid the typical windows UAC dialog boxes.

If you _really_ need at 32 bit version i may look into it, but the electron community advice against this because of several issues.
