### ISSUE TITLE
Add a 'Resumed' or 'Started' filter/label in the left pane

### ISSUE THREAD

**Issue by valdotdev** [tympanix/Electorrent#13]
Along with the usual 5 filters, It would be really helpful if I can see just the active (downloading) torrents. Maybe you can re-label 'Downloading' to 'All' and the new 'Downloading' would only be for active torrents.

**Comment by Tympanix** [comment]
This is true. Because different bittorrent clients have different notions of which torrents are in which state, this becomes a bit ambiguous. For example µTorrent has _started_, _paused_ and _stopped_ where qBittorrent simply has _started_ and _paused_. Right now the _Downloading_ filter includes torrents that are:

* Currently downloading
* Paused but not complete
* Queued for downloading

Following your recommendation, which of the above should define the new _Downloading_ filter?

**Comment by valdotdev** [comment]
I guess _Currently downloading_ would do it since it should be actively downloading the torrent.

**Comment by valdotdev** [comment]
@Tympanix Thanks for 8574c9b4b1d7a2fa2f9c162bf1e698d1d173efd3! But since the All and Downloading filters behave like qBit, I think it still needs that Resumed filter. 😄

**Comment by tympanix** [comment]
In 4d6061a I have removed paused torrents from _Downloading_ and put them in the _Stopped_ tab.

**Comment by tympanix** [comment]
(not the hardest issue to fix, but man did I put this one off) 😆
