### ISSUE TITLE
Download files to local machines

### ISSUE THREAD

**Issue by ghost** [tympanix/Electorrent#135]
Not sure whether it would be within the purview of this app but it certainly would be handy of being able to download completed files from the remote node to the local machine. As of now such action requires the tedious process of logging into the remote node via other means.

**Comment by tympanix** [comment]
While I love your idea, it is sadly a bit out of purview of the app. This is because Electorrent only serves to communicate with the API of popular torrent clients. Few (if any) of the APIs supports the option to download files locally, which means one would need to go beyond the capabilities of the API to achieve this implementation. If (as we may be forced to) the transport mechanism of local files is to be completely detached from the API itself, then it would require 3rd party programs to run on the remote machine. We would have to decide on a protocol (amongst other issues).

If by any means one of the APIs supports this feature I would gladly look into it. That would however result in only supporting those clients explicitly.
