### ISSUE TITLE
Support for qBittorrent API 4.1.x

### ISSUE THREAD

**Issue by n8v8R** [tympanix/Electorrent#136]
**Client:**
-  qbittorrent-nox

**Client Version:**

4.1.5 

**Operating System:**
- client - ubuntu cosmic with 4.18.0-13 kernel
- app - W10 Pro v1809 _x64

**Application Version:**

2.5.0

**Description:**
Having update the client from v 4.1.4 to 4.1.5 the app connection to the client gets lost soon after being initialized.

Reading the changelog https://www.qbittorrent.org/news.php it might be that the API has been updated or that protective measures introduced and thus impeding connectivity.
The client's webgui is accessible via web browser however.

**Comment by tympanix** [comment]
Apparently the API has been completely redesigned from version 4.1.x and up (according to the wiki https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation). Support for this will require a whole new qBittorrent API implementation while still maintaining support for older versions.

**Comment by n8v8R** [comment]
with 4.1.4 it worked fine. Not sure there has been such a drastic change with 4.1.5

**Comment by tympanix** [comment]
Looking at the documentation again you are right about the v2.3.0 API. I was mislead. The `API2` as it is called was introduced in v2.3.0. It is implied meaning `/login` (deprecated) is the same as using `/api/v2/auth/login`.

**Comment by tympanix** [comment]
For future reference the old API instated at v3.2.0 is still valid and useable in v4.x.x. The new API instated at v4.1.x (URIs prefixed with `/api/v2/`) is only applicable from that version onwards. If the legacy API is removed in the future we will have to move to the new API calls (and maybe ditch legacy support). The problems regarding this issue was due to unstable code/inconsistence where authentication cookies was not send to the server properly.
