### ISSUE TITLE
Electorrent on Windows Store?

### ISSUE THREAD

**Issue by Ansem93** [tympanix/Electorrent#147]
Hi,
I wonder if it would be possible to have it one the windows store. I'm finding it very usefull since I don't have to manage update and it do it everything by itself.

**Comment by tympanix** [comment]
Electorrent has its own update mechanism which works quite well. Although I could put it on Windows Store, that would mean I would have to manage updates differently across platforms (Linux/macOS/Windows). Then I would probably also have to put it one the AppStore, and developer accounts costs money. Since this app is free and open source having everything on GitHub is nice.
