### ISSUE TITLE
routines:OPENSSL_internal:WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Venipa** [tympanix/Electorrent#154]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [x] rTorrent
- [ ] Deluge

**Client Version:**
Latest

**Operating System:**
Windows 10 1903

**Application Version:**
2.6.0

**Description:**
Error
```
Error: write EPROTO 769044072:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:


    at WriteWrap.afterWrite [as oncomplete] (net.js:788)
(anonymous) @ welcome.js:22
processQueue @ angular.js:16696
(anonymous) @ angular.js:16712
$eval @ angular.js:17994
$digest @ angular.js:17808
(anonymous) @ angular.js:18033
completeOutstandingRequest @ angular.js:6045
(anonymous) @ angular.js:6324
setTimeout (async)
Browser.self.defer @ angular.js:6322
$evalAsync @ angular.js:18031
(anonymous) @ angular.js:16603
scheduleProcessQueue @ angular.js:16712
$$reject @ angular.js:16772
reject @ angular.js:16766
(anonymous) @ angular.js:16681
_callbacks.(anonymous function) @ remote.js:78
_eventListener @ remote.js:48

```

**Comment by tympanix** [comment]
This seems very odd. Could this by any chance be TLSv1.3 at play? If you can confirm which TLS version the server uses that would be of great help. Thanks for reporting.

**Comment by Venipa** [comment]
dont have really access to the server.
but according to sftp it uses tlsv1.2

**Comment by tympanix** [comment]
Ok. I don't have much control here because the error stems from`net.js` in nodejs and ultimately some C++ third party dependency (boringssl) which means I have little to no way of fixing it in the Electorrent codebase. I'm guessing it must be either:
* Bad server configuration
* Some HTTP/TLS protocol discrepancy between nodejs and the web server

Since I will have a hard time to reproduce the error my best option is to hope it is worked out when I update the nodejs version of Electorrent
