### ISSUE TITLE
Can't connect to any client that is on my seedbox

### ISSUE THREAD

**Issue by Animalwithstix** [tympanix/Electorrent#188]
**Client:**
- [ ] µTorrent
- [x] qBittorrent
- [x] Transmission
- [ ] rTorrent
- [x] Deluge

**Client Version:**
Deluge 2.03
Transmission 3.0
qbittorrent 4.2.5
**Operating System:**
Ubuntu 20.04
**Application Version:**
Current version on MAC OSX catalina
**Description:**
I cannot connect to any of these clients or daemons that run on my seedbox from rapidseedbox.  Every time I try I get the "Connection could not be established". Sometimes I get to the point where it asks me to trust a certificate, which I do but it just disconnects and gives me the same message.I have tried using the seedbed's IP address, "localhost", "127.0.0.1" along with every open port listed in their configuration files.  I have also tried using the different ports for SSH, FTP, SFTP along with 443 and any open ports available.  I have followed instruction provided for this app and from the client providers for connecting to each clients daemon via a remote and I can't get anything to connect.  I know I must be doing something wrong here

**Comment by tympanix** [comment]
Sometimes there might be problems with seedboxes. Generally, you want to use the hostname and port which serves the web UI on your seedbox. Take note if the web UI is served under a special path, and enter that root path in the Electorrent connection details. Also, if your seedbox is using a certificate, check which hostname the certificate is issued to. Even though it works in firefox/chrome etc., Electorrent (or NodeJS actually) requires the connection hostname to match the certificate exactly. Normally, certificates are not issued to an IP address, which is why that generally won't work.

If your seedbox provider uses some custom authentication mechanism (i.e. a login page or similar), Electorrent will not be aware of this custom login mechanism. Electorrent support basic and digest auth.

If you find that Electorrent is missing some implementation to connect to your seedbox provider, once you figure out what and why, we can look at supporting that.
