### ISSUE TITLE
Ubuntu - Can't upload torrent files

### ISSUE THREAD

**Issue by leemm** [tympanix/Electorrent#281]
**Client:**
- [ ] µTorrent
- [&check;] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**
2.7.3

**Operating System:**
Ubuntu 20.04

**Application Version:**
4.4.5

**Description:**
I have a windows 10 box running the latest qBittorrent. I can remotely access it through the webui, and can add torrent files from my Ubuntu 20.04 box.

However, with Electorrent I can connect and view the list of torrents, modify, and delete them. But whenever I try to add by browsing for a torrent file the dialog disappears but the torrent is never added. It appears to be an issue with adding via url too.

Turning on debug and viewing the console shows nothing, as if nothing has been attempted.

**Comment by leemm** [comment]
I looked into this myself.

If I clone and run the app locally, adding a torrent works. Using the released linux binary doesn't.

I tried to build the AppImage myself but for some unknown reason it won't build correctly. Running `npm run dist` results in the binaries being built, but this error when running the AppImage:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@electron/remote/main'
Require stack:
- /tmp/.mount_ElectotFHTzN/resources/app/app.js
```

If I extract the asar file I can see that .@electron. is missing from node_modules. Does this happen to you too? 

node v16.17.0
electron-builder v22.14.5

**Comment by tympanix** [comment]
Hi @leemm 

Thank you for debugging. Good news that the upload feature is working on master. Master branch includes a lot of changes (including a rewrite to typescript, new Electron version, bug fixes, new features and more). I'm currently in the processes of finishing up and performing automated testing.

Your problem with the "@electron" folder missing in the "node_modules" folder might have been caused by the migration to the "@electron/remote" package. We would need to add that to the "app/package.json" file to ensure it is provided in the the asap file as well (since it is a runtime dependency).

**Comment by leemm** [comment]
Thanks @tympanix. Can confirm than cloning master, running `npm run dist` creates an AppImage that works great in Ubuntu 20.04. Thanks for your work on this.
