### ISSUE TITLE
Question regarding words or letters inside square brackets [ ]

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#37]
Whenever I add a torrent, the torrent name with words inside square brackets which are at the start of the string gets moved at the end of said string. Not sure if this is an intended behavior.
Example:
torrent name (input): "**[ABCD]** XXXXX12345 [abcd] [1234].zip"
torrent name (when added to the queue/list): "XXXXX12345 [abcd][1234].zip **[ABCD]**"

**Comment by Tympanix** [comment]
This seems odd. I will have to do some experimentation to figure this one out

**Comment by valdotdev** [comment]
Thanks a lot! 👍

**Comment by Tympanix** [comment]
I can inform you that this is intended behavior. In the early days, the code was partly inspired by another project which cleaned up torrent names as seen in [this function](https://github.com/Tympanix/Electorrent/blob/master/scripts/bittorrent/abstracttorrent.js#L7). It replaces all underscores and periods with spaces to make the name more readable. Furthermore any occurrences of text inside brackets will be moved to the back because it is seen as metadata. Metadata is less important than the actual name, so we want the name to come first and potential metadata afterwards.

I could make a setting where you can turn off automatic clean up of torrent names?

**Comment by valdotdev** [comment]
I could see advantages with this behavior but only for some of my torrents. Having the option to turn  it off would be helpful. :)

**Comment by Tympanix** [comment]
Continued in #38
