### ISSUE TITLE
Deluge support

### ISSUE THREAD

**Issue by mrjonny2** [tympanix/Electorrent#81]
Is there any chance of adding deluge support to the app?

**Comment by Tympanix** [comment]
As far as I can see, Deluge has a pretty well documented API so this is definitely possible. It will however be in the next major release of Electorrent. Thanks for reporting.

**Comment by markcarver** [comment]
Would really like to see this happen. I had to switch from rTorrent to Deluge due to Sonar being unable to remove torrents automatically from rTorrent.

<img width="1019" alt="screen shot 2018-10-18 at 11 17 26 am" src="https://user-images.githubusercontent.com/351902/47168815-7d75d800-d2c7-11e8-931b-4607b266cb57.png">
