### ISSUE TITLE
support for Windows 32 bit 

### ISSUE THREAD

**Issue by BlackGhost3** [Tympanix/Electorrent#91]
will there be future support/release  for win 32bit ?

**Comment by Tympanix** [comment]
I remember there being some problems with 32 bit windows on the Electron platform. As of now it is not planned, but I will be sure to revisit the topic. I will get back to you when I have any news.

([possible solution](https://www.electron.build/configuration/target))

**Comment by Tympanix** [comment]
I have researched the possibility of releasing a 32 bit version of the app. Apparently the issue has not been resolved since I last got involved in the topic - there is a inherent incompatibility with the [release server](https://github.com/GitbookIO/nuts) and the [Squirrel platform](https://github.com/GitbookIO/nuts). The following warning is presented in the console:

`For windows consider only distributing 64-bit or use nsis target, see https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214851130`

There is a long list of forum posts and issues on this topic, something I do not intend to get involved in. For any one requiring a 32 bit version of the application I suggest you compile it yourself - which is not that hard. I will however not be able to release them myself until the app is migrated to NSIS, which forces we to redeploy the update platform from the ground up.

I may be able to write a short compilation tutorial on wiki if you desire. Get back to me if this would be appreciated.
